name: Deploy Static Site

on:
  push:
    branches:
      - main   # change if needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public   # change to your folder (dist/build/public)

      - name: Deploy site
        uses: actions/deploy-pages@v4